### ISSUE TITLE
balltracker_classification.caffemodel for transferlearning

### ISSUE THREAD

**Issue by JosjaG** [Hornobster/Ball-Tracking#2]
Hi, I would like to use your balltracker_classification.caffemodel and use it as a pre-trained model for transferlearning (to save training-time). Would you mind adding it to your repository? Thanks in advance!

**Comment by Hornobster** [comment]
Hi, I am afraid I don't have the trained models anymore.
However, if you are going to use it for transfer learning, you could just plug a good model in, from Caffe's model zoo.
