### ISSUE TITLE
Python 3.5.2 on Windows

### ISSUE THREAD

**Issue by edrossy** [Hornobster/Ball-Tracking#3]
Got the following error:
TypeError: No conversion path for dtype: dtype('<U5')

Lines 144-146 & 227-229 (generate_dataset_multithreaded.py) updated to:
dset.attrs['CLASS'] = 'IMAGE'
dset.attrs['VERSION'] = '1.2'
dset.attrs['IMAGE_SUBCLASS'] = 'IMAGE_GRAYSCALE'

Now running fine. May decide to branch off project to support running in Windows environment.

**Comment by Hornobster** [comment]
If you want, create a pull request and I'll integrate the change.
